import { Project } from "@/types/project";

export const seedProjects: Project[] = [
  {
    id: "project-flow",
    name: "Flow Productivity App",
    slug: "flow-productivity",
    description: "A full-stack productivity web application designed to structure daily workflows, schedule tasks, and minimize distractions.",
    longDescription: "Flow is a personal productivity system designed to help developers and creatives structure their daily workflows. It combines task scheduling, focus session timers, and distraction-blocking utilities into a single unified workspace. By storing real-time session states, users can seamlessly track focus logs across multiple devices.\n\nKey Highlights:\n- Real-time task syncing and workflow tracking\n- Minimal, distraction-free interface matching a clean developer aesthetic\n- Persistent session logging with secure authentication",
    websiteUrl: "https://flow.anshul.space",
    githubUrl: "https://github.com/anshul606",
    imageUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80",
    faviconUrl: "https://github.com/favicon.ico",
    techStack: ["React", "Next.js", "Tailwind CSS", "Firebase", "Node.js"],
    features: [
      "Task scheduling with daily drag-and-drop workflow planner",
      "Interactive focus timers with background noise blocks",
      "Persistent cloud database synced via Firebase Firestore",
      "Interactive analytics dashboard tracking weekly focus metrics"
    ],
    status: "live",
    role: "Full-Stack Developer",
    year: "2026",
    system: "Web Application",
    createdAt: new Date("2026-01-10").toISOString(),
    updatedAt: new Date("2026-01-10").toISOString(),
  },
  {
    id: "project-tars",
    name: "Tars Real-Time Chat",
    slug: "tars-chat",
    description: "An AI-scaffolded, real-time chat application supporting instant messaging, group channels, and auth integrations.",
    longDescription: "Tars is a real-time messaging application engineered end-to-end within 2-3 hours using an autonomous, agent-based AI development loop. It showcases rapid prototyping workflows and solid architectural choices like serverless instant messaging databases and integrated session-token management.\n\nHighlights:\n- Synchronized group channels and private chats\n- Automated AI agent prompting to scaffold base models and UI layout\n- Instant message delivery with sub-second websocket sync",
    websiteUrl: "https://tars.anshul.space",
    githubUrl: "https://github.com/anshul606",
    imageUrl: "https://images.unsplash.com/photo-1611605698335-8b15d27e03f2?auto=format&fit=crop&w=1200&q=80",
    faviconUrl: "https://github.com/favicon.ico",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Convex", "Clerk", "Shadcn UI"],
    features: [
      "Real-time websocket messaging synced instantly via Convex",
      "Integrated secure authentication flow using Clerk SDK",
      "Responsive, clean UI featuring dark/light aesthetic rules",
      "Custom emoji reactions and typing-indicator feeds"
    ],
    status: "live",
    role: "Lead Developer",
    year: "2026",
    system: "Web Application",
    createdAt: new Date("2026-02-15").toISOString(),
    updatedAt: new Date("2026-02-15").toISOString(),
  },
  {
    id: "project-synapse-shader",
    name: "SYNAPSE SHADER ENGINE",
    slug: "synapse-shader-engine",
    description: "An experimental WebGL node graph editor mapping neural pathways to synthetic sound waves.",
    longDescription: "Synapse Shader Engine is an interactive canvas built at the intersection of neuroscience and procedural music synthesis. It allows users to visually connect nodes representing simulated brainwaves (Alpha, Beta, Theta) and translate them into mathematical shader modifiers and real-time audio oscillators in the browser.\n\nKey Technologies:\n- React & Three.js for node-graph state management and canvas layout\n- Custom GLSL Fragment Shaders mapping audio frequencies to color outputs\n- Web Audio API oscillators representing brainwave patterns",
    websiteUrl: "https://github.com/anshul606/synapse",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
    faviconUrl: "https://github.com/favicon.ico",
    techStack: ["Three.js", "WebGL", "Web Audio API", "React", "TypeScript"],
    features: [
      "Custom procedural node-graph interface with canvas connections",
      "GLSL fragment shader live editing and compilation",
      "Dynamic Web Audio oscillators with custom ADSR envelopes",
      "Save/Export project nodes as JSON configurations"
    ],
    status: "wip",
    role: "Lead Developer",
    year: "2026",
    system: "Graphics Engine",
    createdAt: new Date("2026-05-12").toISOString(),
    updatedAt: new Date("2026-05-12").toISOString(),
  },
  {
    id: "project-nexus-db",
    name: "NEXUS DISTRIBUTED DB",
    slug: "nexus-db",
    description: "A lightweight, type-safe distributed key-value store optimized for low-latency memory operations.",
    longDescription: "Nexus DB is a systems engineering project focusing on distributed consensus and high-throughput memory caching. Built in Rust, it utilizes a custom protocol and implements the Raft consensus algorithm to maintain database state sync across dynamic node clusters. A TypeScript client library wraps the database for type-safe applications.\n\nFeatures:\n- Implements Raft consensus for state replication\n- Zero-copy deserialization using FlatBuffers\n- Async I/O engine powered by Tokio",
    websiteUrl: "https://github.com/anshul606",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    faviconUrl: "https://github.com/favicon.ico",
    techStack: ["Rust", "gRPC", "Tokio", "TypeScript", "Raft Protocol"],
    features: [
      "Sub-millisecond write latencies at scale",
      "Consensus-driven cluster node scaling and self-healing",
      "Native type definition compiler for client libraries",
      "Lightweight command-line CLI dashboard for cluster status"
    ],
    status: "live",
    role: "Systems Engineer",
    year: "2025",
    system: "Distributed System",
    createdAt: new Date("2025-11-04").toISOString(),
    updatedAt: new Date("2025-11-04").toISOString(),
  }
];
